In [2]:
from sklearn.datasets import load_iris
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
pd.pandas.set_option('display.max_columns',None)
iris = load_iris()

X = iris.data

y = iris.target

In [33]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [22]:
from sklearn.neighbors import KNeighborsClassifier

In [23]:
knn = KNeighborsClassifier(n_neighbors=1)

In [26]:
knn.fit(X,y)

KNeighborsClassifier(n_neighbors=1)

In [29]:
#da doi phai pass array moi chay
#tra lai 2 la respond 2 
knn.predict([[3,5,4,2]])

array([2])

In [40]:
X_new = ([3,5,4,2],[3,4,2,1])
knn.predict(X_new)

array([2, 0])

In [41]:
#doi k = 5
knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(X,y)

KNeighborsClassifier()

In [42]:
knn.predict([[3,5,4,2]])


array([1])

In [43]:
X_new = ([3,5,4,2],[3,4,2,1])
knn.predict(X_new)

array([1, 0])

In [44]:
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression()

logreg.fit(X,y)

logreg.predict(X_new)

C:\Users\TRAN TU VAN\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0, 0])

In [ ]:
discrete_feature=[feature for feature in load_iris if len(load_iris[feature].unique())<25]